fftshift!(dst, src) = circshift!(dst, src, div.([size(src)...],2))
ifftshift!(dst, src) = circshift!(dst, src, div.([size(src)...],-2))
function myfft!(img, tmp)
    ifftshift!(tmp, img)
    fft!(tmp)
    fftshift!(img, tmp)
end
function myifft!(img, tmp)
    ifftshift!(tmp, img)
    ifft!(tmp)
    fftshift!(img, tmp)
end
x = rand(ComplexF32, 16, 16)
y = rand(ComplexF32, 16, 16)
fftshift(fft(ifftshift(y)))
ifftshift!(x, y)
fft!(x)
fftshift!(y, x)
myfft!(y, x)
